#include <string>
#include <map>

extern const std::map<std::string, std::string> resource2c = {
    {"./resources/axis.f.glsl",
        "out vec4 color;\n"
        "\n"
        "void main(void) {\n"
        "	color = vec4(0, 0, 0, 0);\n"
        "}\n"
        ""},
    {"./resources/axis.v.glsl",
        "in vec2 a_coord;\n"
        "uniform float width;\n"
        "uniform float height;\n"
        "uniform vec2 origin;\n"
        "\n"
        "void main(void) {\n"
        "	vec2 true_coord = a_coord + origin;\n"
        "	gl_Position = vec4(true_coord.x / width - 0.5, true_coord.y / height - 0.5, 0, 0.5);\n"
        "}\n"
        ""},
    {"./resources/graph.f.glsl",
        "uniform vec4 color;\n"
        "out vec4 color_out;\n"
        "\n"
        "void main(void) {\n"
        "	color_out = color;\n"
        "}\n"
        ""},
    {"./resources/graph.v.glsl",
        "in float val;\n"
        "uniform float width;\n"
        "uniform float inverse_x_scale;\n"
        "uniform float height;\n"
        "uniform float y_scale;\n"
        "uniform float y_max;\n"
        "uniform vec2 origin;\n"
        "\n"
        "void main(void) {\n"
        "	float value = val < y_max ? val : y_max;\n"
        "	gl_Position = vec4(\n"
        "		(float(gl_VertexID) / inverse_x_scale + origin.x) / width - 0.5,\n"
        "		(value * y_scale + origin.y) / height - 0.5,\n"
        "		0,\n"
        "		0.5);\n"
        "}\n"
        ""},
    {"./resources/heatmap.f.glsl",
        "in float fs_val;\n"
        "\n"
        "out vec4 color;\n"
        "\n"
        "uniform sampler2D gradient;\n"
        "\n"
        "void main(void) {\n"
        "	color = texture(gradient, vec2(fs_val, 0.5));\n"
        "}\n"
        ""},
    {"./resources/heatmap.v.glsl",
        "in float i_val;\n"
        "\n"
        "out float fs_val;\n"
        "\n"
        "uniform float min_val;\n"
        "uniform float max_val;\n"
        "uniform int value_count;\n"
        "uniform int series_count;\n"
        "uniform int series_buffer_offset;\n"
        "\n"
        "\n"
        "uniform float width;\n"
        "uniform float height;\n"
        "uniform vec2 origin;\n"
        "\n"
        "uniform float window_width;\n"
        "uniform float window_height;\n"
        "\n"
        "void main(void) {\n"
        "	fs_val = (i_val - min_val) / (max_val - min_val); \n"
        "\n"
        "	int x = gl_VertexID % value_count;\n"
        "	int y = gl_VertexID / value_count;\n"
        "	y = (y - series_buffer_offset + series_count) % series_count;\n"
        "	vec2 coord = vec2(\n"
        "		float(x) * width / float(value_count),\n"
        "		float(y) * height / float(series_count));\n"
        "	vec2 true_coord = coord + origin;\n"
        "\n"
        "	gl_Position = vec4(\n"
        "		true_coord.x / window_width - 0.5,\n"
        "		true_coord.y / window_height - 0.5,\n"
        "		-0.5, // TODO: z-index in all shaders\n"
        "		0.5);\n"
        "}\n"
        ""},
    {"./resources/simple_color.f.glsl",
        "flat in int fs_color_index;\n"
        "\n"
        "out vec4 color;\n"
        "\n"
        "uniform sampler2D color_map;\n"
        "\n"
        "void main(void) {\n"
        "	color = texelFetch(color_map, ivec2(fs_color_index, 0), 0);\n"
        "}\n"
        ""},
    {"./resources/simple_color.v.glsl",
        "in vec2 a_coord;\n"
        "in float color_index;\n"
        "\n"
        "flat out int fs_color_index;\n"
        "\n"
        "uniform float width;\n"
        "uniform float height;\n"
        "uniform vec2 origin;\n"
        "\n"
        "void main(void) {\n"
        "	fs_color_index = int(color_index);\n"
        "\n"
        "	vec2 true_coord = a_coord + origin;\n"
        "	gl_Position = vec4(true_coord.x / width - 0.5, true_coord.y / height - 0.5, 0, 0.5);\n"
        "}\n"
        ""},
    {"./resources/single_color.f.glsl",
        "out vec4 o_color;\n"
        "\n"
        "uniform vec4 color;\n"
        "\n"
        "void main(void) {\n"
        "	o_color = color;\n"
        "}\n"
        ""},
    {"./resources/text.f.glsl",
        "in vec2 tex_coord;\n"
        "uniform sampler2D text_texture;\n"
        "out vec4 color;\n"
        "\n"
        "void main(void) {\n"
        "	color = texture(text_texture, tex_coord);\n"
        "}\n"
        ""},
    {"./resources/text.v.glsl",
        "in vec2 a_coord;\n"
        "in vec2 a_tex_coord;\n"
        "out vec2 tex_coord;\n"
        "uniform float width;\n"
        "uniform float height;\n"
        "uniform vec2 pos;\n"
        "\n"
        "void main(void) {\n"
        "	tex_coord = vec2(a_tex_coord.x, 1.0-a_tex_coord.y);\n"
        "	vec2 true_coord = a_coord + pos;\n"
        "	gl_Position = vec4(true_coord.x / width - 0.5, true_coord.y / height - 0.5, 0, 0.5);\n"
        "}\n"
        ""}
};
